name: groot
version: "0.0.1"
description: 实时问答社区
keywords: "go, gorm, mysql, socket, iris, angular"

admin:
  - "dm@123.com"
  - "skr@123.com"

db: "mysql:ThisISmysql@tcp(db:3306)/groot?charset=utf8&parseTime=True&loc=Local"

departments:
  - "技术部"
  - "人事部"
  - "财务部"
  - "其它"

session_secret: "racconandgroot"
